name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: RustFmt
      run: cargo fmt --all -- --check

    - name: Stack
      run: docker-compose -f docker/docker-compose.yml up --build -d

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
